### ISSUE TITLE
Round values when you mouse over on the charts

### ISSUE THREAD

**Issue by tarasbob** [PredictionExplorer/augur-explorer#100]
When you mouse over the profit/loss history chart on the user page, sometimes the values can be very long (like 34.4524525245). Let's just round it to the nearest dollar. Let's do this for all the charts on the site.

**Comment by smartgru** [comment]
@tarasbob 
may I fix it as 2 decimal points?

**Comment by tarasbob** [comment]
Ok, sure, let's round to 2 decimal places.
