### ISSUE TITLE
If the market is finalized, display the finalized result on the market detail page

### ISSUE THREAD

**Issue by tarasbob** [PredictionExplorer/augur-explorer#107]
Let's display the reported outcome on the market detail page if the market is finalized.

**Comment by smartgru** [comment]
@tarasbob 
Could you please describe more about this task?

**Comment by tarasbob** [comment]
After a market is finalized (enable "show finalized markets" on the front page), we want to display what the result is. For example, in the presidential election market, if Joe Biden wins, we will want to display that the winning outcome is "Joe Biden". Look at this market for example, https://predictionexplorer.com/market/0xE38f69f1ECbe8009a0F2baA44000E5bA9982948b We can't tell what actual the outcome is.
