### ISSUE TITLE
Various changes to the market detail page

### ISSUE THREAD

**Issue by tarasbob** [PredictionExplorer/augur-explorer#63]
Feel free to break this up into multiple issues.

- [x] We want to sort outcomes based on probability in the order of likelyhood. The most likely outcome should be at the top.
- [x] The invalid outcome should always be at the bottom. If it has a probability higher than INVALID_THRESHOLD, it should be visible. If it has a probability lower than INVALID_THRESHOLD then it should not be visible, however, there should be a UX element that will make it make it appear if the user interacts with the UX element.
- [x] Display bid and ask prices correctly when `view details` button is pressed.
- [x] Make sure the open bid and open ask orders are loaded correctly when the user clicks on `depth chart`. The depth chart needs to be drawn correctly. It is not drawn correctly now.
- [x] If all the open bid and ask orders are already shown on the page, the `load more` should be disabled or removed.
- [x] `Total volume` is not displayed correctly
- [x] The `Advanced` section does not look like in the design.
- [x] The contents of `Category` under `Advanced` is not displayed correctly.
- [x] `Filled orders` is not displayed correclty. If all the filled orders are already displayed, the `Load more` button should be disabled or removed.
- [x] The chart does not look right. There should be a way to select which outcomes to display on the chart. There should be a way to select a date range. It should be possible to make the chart full screen.
- [x] The page does not look right on a mobile device.

**Comment by smartgru** [comment]
1. Ascending or Descending?
2. We set INVALID_THRESHOLD as 5% in Market list page, Can we use it also on Market detail page?

**Comment by tarasbob** [comment]
1. It should be descending (just like on the front page).
2. Let's use the same INVALID_THRESHOLD on both the front page and the market detail page. Let's set the INVALID_THRESHOLD to 10%.
