### ISSUE TITLE
Make the search bar work

### ISSUE THREAD

**Issue by tarasbob** [PredictionExplorer/augur-explorer#74]
We want the search bar to work similarly to how it works on this page: https://etherscan.io/

When you start typing it would be searching in
- Add full text search in Market description field using full-text search option in Postgres. Additionally rank results using Volume and Frozen funds fields to show most traded markets first.
- User addresses
- Market address

It would update after every keystroke. The user experience should be similar to https://etherscan.io

**Comment by smartgru** [comment]
Basically it's finished.
Bugs will be done in another tickets.
